package com.jogocarreira.futebol.data

val COUNTRIES = listOf(
    "Brasil",
    "Argentina",
    "Uruguai",
    "Chile",
    "Colômbia",
    "Paraguai",
    "Peru",
    "Equador",
    "Bolívia",
    "Venezuela",
    "México",
    "Estados Unidos",
    "Canadá",
    "Costa Rica",
    "Panamá",
    "Honduras",
    "El Salvador",
    "Guatemala",
    "Nicarágua",
    "Jamaica",
    "Inglaterra",
    "Espanha",
    "França",
    "Alemanha",
    "Itália",
    "Portugal",
    "Países Baixos",
    "Bélgica",
    "Croácia",
    "Sérvia",
    "Suíça",
    "Áustria",
    "Turquia",
    "Grécia",
    "Escócia",
    "Irlanda",
    "Irlanda do Norte",
    "País de Gales",
    "Polônia",
    "Ucrânia",
    "Rússia",
    "República Tcheca",
    "Eslováquia",
    "Hungria",
    "Romênia",
    "Bulgária",
    "Eslovênia",
    "Bósnia e Herzegovina",
    "Montenegro",
    "Albânia",
    "Macedônia do Norte",
    "Kosovo",
    "Finlândia",
    "Suécia",
    "Noruega",
    "Dinamarca",
    "Islândia",
    "Estônia",
    "Letônia",
    "Lituânia",
    "Estados Unidos",
    "Japão",
    "Coreia do Sul",
    "China",
    "Austrália",
    "Arábia Saudita",
    "Catar",
    "Emirados Árabes Unidos",
    "Irã",
    "Iraque",
    "Israel",
    "Jordânia",
    "Uzbequistão",
    "Tailândia",
    "Vietnã",
    "Indonésia",
    "Malásia",
    "Índia",
    "Egito",
    "Marrocos",
    "Argélia",
    "Tunísia",
    "Nigéria",
    "Gana",
    "Costa do Marfim",
    "Senegal",
    "Camarões",
    "África do Sul",
    "Mali",
    "Guiné",
    "Burkina Faso",
    "República Democrática do Congo",
    "República do Congo",
    "Gabão",
    "Angola",
    "Moçambique",
    "Zâmbia",
    "Zimbábue",
    "Uganda",
    "Quênia",
    "Tanzânia",
    "Etiópia",
    "Sudão",
    "Líbia",
    "Benim",
    "Togo",
    "Níger",
    "Burundi",
    "Ruanda",
    "Namíbia",
    "Botsuana",
    "Madagascar",
    "Cabo Verde",
    "Guiné-Bissau",
    "Guiné Equatorial",
    "Serra Leoa",
    "Libéria",
    "Gâmbia",
    "Mauritânia",
    "Comores",
    "Maurício",
    "Nova Zelândia",
    "Fiji",
    "Papua-Nova Guiné",
    "Haiti",
    "Cuba",
    "Trinidad e Tobago",
    "República Dominicana",
    "Porto Rico",
    "China",
    "Hong Kong",
    "Taiwan",
    "Singapura",
    "Filipinas",
    "Mianmar",
    "Bangladesh",
    "Paquistão",
    "Nepal",
    "Sri Lanka",
    "Afeganistão",
    "Síria",
    "Líbano",
    "Palestina",
    "Kuwait",
    "Bahrein",
    "Omã",
    "Iêmen",
    "Cazaquistão",
    "Quirguistão",
    "Tajiquistão",
    "Turcomenistão",
    "Azerbaijão",
    "Armênia",
    "Geórgia",
    "Moldávia",
    "Belarus",
    "Malta",
    "Chipre",
    "Luxemburgo",
    "Liechtenstein",
    "Andorra",
    "San Marino",
    "Mônaco",
    "Vaticano",
    "Mongólia",
    "Brunei",
    "Camboja",
    "Laos",
    "Timor-Leste",
    "Maldivas",
    "Butão",
    "Afeganistão",
    "Bahamas",
    "Barbados",
    "Belize",
    "Bermudas",
    "Granada",
    "Guiana",
    "Suriname",
    "Antígua e Barbuda",
    "Dominica",
    "Santa Lúcia",
    "São Cristóvão e Névis",
    "São Vicente e Granadinas",
    "Aruba",
    "Curaçao"
)
